### ISSUE TITLE
Clients are required to have this mod installed if host has it installed

### ISSUE THREAD

**Issue by Agitatio** [krzysztof-ciszewski/CustomizableCorruptionMeter#1]
I was expecting it to be client-side like most other HUD mods, but as the title says clients need to have it installed too. Is that fixable?

**Comment by krzysztof-ciszewski** [comment]
Yeah, I'll get on that - I thought by default the mod would be client side, but I'll fix it

**Comment by krzysztof-ciszewski** [comment]
The fix is already on thunderstore
